server:
  port: 3344

spring:
  application:
    name: microservicecloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ShinkaYxs/microservicecloud-config.git  # github上的地址



